version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"                # Root directory (adjust if your frontend is in /client or /frontend)
    schedule:
      interval: "daily"          # Options: "daily", "weekly", "monthly"
    open-pull-requests-limit: 5
    reviewers:
      - "Kroymande"      # GitHub username of who should review PRs
    commit-message:
      prefix: "chore"
      include: "scope"